import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Text, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID, JSONB
from db.base import Base


class BriefDoc(Base):
    """
    设计建议书大纲 (Brief Document Outline)
    Generated by Brief Doc Agent after reference selection.
    Contains the narrative structure for the PPT.
    """
    __tablename__ = "brief_docs"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    package_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True, index=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="draft")  # draft / confirmed

    # Structured outline content (JSON)
    outline_json: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Slot assignments from Outline Agent (JSON array of SlotAssignment dicts)
    slot_assignments_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Free-text narrative summary
    narrative_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    material_summary_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    evidence_keys_json: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
